// generated by the columns. DO NOT EDIT!

#define USE_COLUMN_MACROS
#include <columns.h>

#include "messages.h"

#ifdef __cplusplus
extern "C" {
#endif

// messages.h:4:8
static const clColumn c__S_stUseItemReq[] = {
    DEFINE_FIELD_NUMBER(struct stUseItemReq, itemID),
};
const clColumn stUseItemReqObject[] = {
    DEFINE_OBJECT(struct stUseItemReq, c__S_stUseItemReq),
};
// messages.h:9:8
static const clColumn c__S_stDrop[] = {
    DEFINE_FIELD_NUMBER(struct stDrop, itemID),
    DEFINE_FIELD_NUMBER(struct stDrop, itemNum),
};
const clColumn stDropObject[] = {
    DEFINE_OBJECT(struct stDrop, c__S_stDrop),
};
// messages.h:15:8
static const clColumn c__S_stUseItemRsp[] = {
    DEFINE_FIELD_NUMBER(struct stUseItemRsp, code),
    DEFINE_FIELD_NUMBER(struct stUseItemRsp, num),
    DEFINE_FIELD_OBJECT_FLEXIBLE_ARRAY(struct stUseItemRsp, drops, stDropObject),
};
const clColumn stUseItemRspObject[] = {
    DEFINE_OBJECT(struct stUseItemRsp, c__S_stUseItemRsp),
};
// messages.h:22:7
static const clColumn c__U_stValue[] = {
    DEFINE_FIELD_NUMBER(union stValue, i32),
    DEFINE_FIELD_NUMBER(union stValue, u32),
    DEFINE_FIELD_NUMBER(union stValue, c),
    DEFINE_FIELD_NUMBER(union stValue, u8),
    DEFINE_FIELD_FIXED_ARRAY(union stValue, other),
};
union c__S_stInlineUnion_U_messages_h_406 {
  int32_t i32;
  uint32_t u32;

  char c;
  uint8_t u8;

  uint64_t other[2];
};
// messages.h:34:3
static const clColumn c__S_stInlineUnion_U_messages_h_406[] = {
    DEFINE_FIELD_NUMBER(union c__S_stInlineUnion_U_messages_h_406, i32),
    DEFINE_FIELD_NUMBER(union c__S_stInlineUnion_U_messages_h_406, u32),
    DEFINE_FIELD_NUMBER(union c__S_stInlineUnion_U_messages_h_406, c),
    DEFINE_FIELD_NUMBER(union c__S_stInlineUnion_U_messages_h_406, u8),
    DEFINE_FIELD_FIXED_ARRAY(union c__S_stInlineUnion_U_messages_h_406, other),
};
// messages.h:32:8
static const clColumn c__S_stInlineUnion[] = {
    DEFINE_FIELD_NUMBER(struct stInlineUnion, tag),
    DEFINE_FIELD_UNION(struct stInlineUnion, abc, c__S_stInlineUnion_U_messages_h_406),
};
const clColumn stInlineUnionObject[] = {
    DEFINE_OBJECT(struct stInlineUnion, c__S_stInlineUnion),
};
// messages.h:45:8
static const clColumn c__S_stFuzz[] = {
    DEFINE_FIELD_STRING(struct stFuzz, name),
    DEFINE_FIELD_NUMBER(struct stFuzz, tag),
    DEFINE_FIELD_UNION(struct stFuzz, v, c__U_stValue),
};
const clColumn stFuzzObject[] = {
    DEFINE_OBJECT(struct stFuzz, c__S_stFuzz),
};
// messages.h:51:8
static const clColumn c__S_stTests[] = {
    DEFINE_FIELD_NUMBER(struct stTests, epoch),
    DEFINE_FIELD_STRING(struct stTests, name),
    DEFINE_FIELD_NUMBER(struct stTests, fuzzNum),
    DEFINE_FIELD_OBJECT_FLEXIBLE_ARRAY(struct stTests, fuzz, stFuzzObject),
    DEFINE_FIELD_OBJECT(struct stTests, inlineUnion, c__S_stInlineUnion),
};
const clColumn stTestsObject[] = {
    DEFINE_OBJECT(struct stTests, c__S_stTests),
};

// extra_output 2
#ifdef __cplusplus
}
#endif
