#pragma once

// generated by the columns. DO NOT EDIT!
#include <columns.h>

#ifdef __cplusplus
extern "C" {
#endif
struct clColumn;

extern const struct clColumn stUseItemReqObject[];
extern const struct clColumn stDropObject[];
extern const struct clColumn stUseItemRspObject[];
extern const struct clColumn stInlineUnionObject[];
extern const struct clColumn stFuzzObject[];
extern const struct clColumn stTestsObject[];

// extra_output 1
#ifdef __cplusplus
}
#endif
